### ISSUE TITLE
I get an error in OpenSuSe

### ISSUE THREAD

**Issue by aligoren** [krikmo/Remarkable#1]
Hi. Thanks for your work. But i get an error my OpenSuSe linux:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 29, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 28, in <module>
    from gi.repository import WebKit
  File "/usr/lib64/python3.4/site-packages/gi/importer.py", line 144, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit, introspection typelib not found
```

How can i solve this?

**Comment by krikmo** [comment]
Hey there @aligoren,

I only posted this here because the creator is rewriting the software and decided not to share the source code. 

Please post your issue [here](https://github.com/remarkableapp/Remarkable-Linux/issues) and I'm sure someone (the creator, maybe) will be able to help you out.

Cheers
